import { Flashcard } from "./flashcard";

export const FLASHCARDS: Flashcard[] = [
    {
        id: 1,
        source: 'samochód',
        target: 'Auto',
        sourceLang: 'pl',
        targetLang: 'de',
        isHidden: true,
    },
    {
        id: 2,
        source: 'samochód',
        target: 'Wagen',
        sourceLang: 'pl',
        targetLang: 'de',
        isHidden: true,
    },
    {
        id: 3,
        source: 'bohater',
        target: 'Held(in)',
        sourceLang: 'pl',
        targetLang: 'de',
        isHidden: true,
    },
    {
        id: 4,
        source: 'bohater',
        target: 'verdienter Mensch',
        sourceLang: 'pl',
        targetLang: 'de',
        isHidden: true,
    },
    {
        id: 5,
        source: 'samochód',
        target: 'Last[kraft]wagen',
        sourceLang: 'pl',
        targetLang: 'de',
        isHidden: true,
    },
    {
        id: 6,
        source: 'Haubentaucher',
        target: 'perkoz dwuczuby',
        sourceLang: 'de',
        targetLang: 'pl',
        isHidden: true,
    },
    {
        id: 7,
        source: 'raubeinig',
        target: 'łobuzerski',
        sourceLang: 'de',
        targetLang: 'pl',
        isHidden: true,
    },
    {
        id: 8,
        source: 'delfin',
        target: 'Dolphin',
        sourceLang: 'pl',
        targetLang: 'en',
        isHidden: true,
    },
]